- name: Install dependencies
        run: npm install
        working-directory: site-institucional

      - name: Fix permissions
        run: chmod +x node_modules/.bin/vite
        working-directory: site-institucional

      - name: Build
        run: npm run build
        working-directory: site-institucional
